version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-test-publish:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build files
          command: yarn build
      - run:
          name: Run tests
          command: yarn test
      - when:
          condition:
            equal: ["publish", <<pipeline.git.branch>>]
          steps:
            - run:
                name: Build landing page
                command: |
                  cd landing
                  yarn install
                  yarn build
            - run:
                name: Deploy landing page to Firebase
                command: |
                  cd landing 
                  echo $FIREBASE_HOSTING_KEY_JSON>credentials.json
                  GOOGLE_APPLICATION_CREDENTIALS=credentials.json npx firebase deploy
            - run:
                name: Publish package to NPM
                command: |
                  npm set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
                  npm publish
workflows:
  build-test-publish:
    jobs:
      - build-test-publish
