version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-test-publish:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build files
          command: yarn build
      - run:
          name: Run tests
          command: yarn test
      - when:
          condition:
            equal: ["publish", <<pipeline.git.branch>>]
          steps:
            - run:
                name: Set NPM auth token
                command: npm set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
            - run:
                name: Publish to NPM
                command: npm publish
      - run:
          name: Install landing project dependencies
          command: |
            cd landing
            yarn install
      - run:
          name: Deploy landing project to Firebase
          command: |
            cd landing 
            echo $FIREBASE_HOSTING_KEY_JSON>credentials.json
            GOOGLE_APPLICATION_CREDENTIALS=credentials.json 
            npx firebase deploy
workflows:
  build-test-publish:
    jobs:
      - build-test-publish
