apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: npm-deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    steps:
      - uses: node:20.11.1
        name: Run tests
        shell: sh
        run: >-
          node -v
          npm -v


          # Install yarn
          npm i -g yarn@1.22.22
          yarn -v


          # Install dependencies
          yarn install


          # Run tests
          yarn test
